# Generated by Django 5.0.6 on 2024-07-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
